### ISSUE TITLE
Windows (Ubuntu on WSL2) initialization of db fails for aquarium-local

### ISSUE THREAD

**Issue by jdbishop** [klavinslab/aquarium-local#1]
Aquarium failed to initialize on Windows 10 (Ubuntu on WSL2 within Windows Terminal after installing Docker Desktop, WSL2, Ubuntu from Microsoft Store) with the following error:
```db_1            | Initializing database
db_1            | 2021-01-20T19:57:21.267561Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1            | 2021-01-20T19:57:21.270228Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
db_1            | 2021-01-20T19:57:21.270295Z 0 [ERROR] Aborting
db_1            |
```

I was able to get aquarium-local to initialize and run on my Windows 10 machine by making three changes (one specified and two unspecified in the docs) to the docker-compose.yml configuration file included in the distro (see my updated "db" section from the docker-compose.yml file). Maybe update the docker-compose.yml file?

```
  db:
    # --changed from 5.7 to 5.7.16 --
    image: mysql:5.7.16
    #-----------------------------------
    # -- added as suggested by docs ----------------------------------------------------------------------------
    command: --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --log_bin=ON --server-id=1
    # --------------------------------------------------------------------------------------------------------------- 
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: ${TIMEZONE}
    volumes:
      # -- removed --------------
      #- ./data/db:/var/lib/mysql
      #----------------------------
      # -- added ---
      - .:/application
      #---------------
      - ./data/mysql_init/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - aquarium_net
```
